### ISSUE TITLE
Version 1.1.3 "Could not determine file type"

### ISSUE THREAD

**Issue by Libidex** [brackets-beautify/brackets-beautify#102]
Hi I am trying to add sass support and have added the following to the brackets.json file

"beautify.sassConvertPath": "/usr/bin/sass-convert"

but i get the following error

JavaScript Alert - file:///
Could not determine file type

I am using Jekyll to currently watch my sass file I do not know if this is causing an error or not.

**Comment by Hirse** [comment]
Please update and reopen this issue if you are still seeing the problem.
