### ISSUE TITLE
less files are not aligned properly

### ISSUE THREAD

**Issue by ShashankaNataraj** [brackets-beautify/brackets-beautify#106]
LESS files are not aligned properly, even if I manually align the less file, it still saves it like this. Is it possible to disable the alignment if the file type isnt supported, or fix this issue?

![capture](https://cloud.githubusercontent.com/assets/650317/4136546/23f6110a-337f-11e4-892e-12e9b6889f4b.JPG)

**Comment by bitwiseman** [comment]
This should be fixed in beautifier 1.5.7.  Please take a look.

**Comment by ShashankaNataraj** [comment]
Im not using brackets anymore. Brackets is the most buggiest editor I have had the displeasure of trying. I have since moved on to webstorm which gives me everything Im looking for.

**Comment by Hirse** [comment]
@ShashankaNataraj, I am sorry you dislike Brackets.
If you ever feel like trying it again, this issue is fixed now.

**Comment by retan** [comment]
Hi
There are still some issues with less. 
First off all variable interpolation.
This 
![image](https://cloud.githubusercontent.com/assets/3779428/18177894/6014877a-707c-11e6-884c-0f5e8df2322a.png)
becoms this
![image](https://cloud.githubusercontent.com/assets/3779428/18177914/73815432-707c-11e6-92b8-b4878db9afb4.png)

Secondly mixins with multiple parameters.
This
![image](https://cloud.githubusercontent.com/assets/3779428/18177997/d9ba5564-707c-11e6-935d-35c5fef876bb.png)
becoms this
![image](https://cloud.githubusercontent.com/assets/3779428/18178011/ecf0b9b6-707c-11e6-98bd-023942a3779d.png)

I would appreciate a fix.
(by the way this extension works a way better than the dedicated Format LESS StyleSheet, which makes a total mess!!)

**Comment by bitwiseman** [comment]
@retan - you might want to pen a new issue and convert your examples to text instead of images.

**Comment by retan** [comment]
@bitwiseman - thanks for the advice. I'll do that.

**Comment by Hirse** [comment]
@bitwiseman Thanks for the guidance. Is this an issue the library could handle?

**Comment by retan** [comment]
@bitwiseman I'm not really sure - I don't know the logic of the code behind it. But I imagine it's only a matter of modifying or adding some regular expressions, e.g. in case of variable interpolation "don't touch it if `{` is prefixed with `@`", in case of mixins parameters "don't add new lines after `;` if you are between `()`, add a one space instead".
