### ISSUE TITLE
Load settings every time from .jsbeautifyrc

### ISSUE THREAD

**Issue by 1951FDG** [brackets-beautify/brackets-beautify#110]
A while ago, https://github.com/drewhamlett/brackets-beautify/pull/54 enabled the usage of .jsbeautifyrc configuration file. Currently, changes made to .jsbeautifyrc are not effective immediately, because .jsbeautifyrc is loaded once only. Current workaround is to restart Brackets for updated settings to apply (e.g., Debug > Reload With Extensions).

Suggestion is to load settings every time before pending operations, similar to [brackets-csslint](https://github.com/cfjedimaster/brackets-csslint).

This may also apply to 'settings.json', but I haven't done any testing.

**Comment by 1951FDG** [comment]
Any update on this?

**Comment by klarkc** [comment]
+1

**Comment by Hirse** [comment]
This is fixed in the next version.
(Instead of loading the settings everytime, we are listening to changes in the settings)
