### ISSUE TITLE
Cant find file type in mixed mode.

### ISSUE THREAD

**Issue by abdelouahabb** [brackets-beautify/brackets-beautify#115]
Hi,

thank you for the extension,

why the extension dont look at the extension simply?

I go an error `Could not determine file type` on a Django/Tornado file (which are just html files).

![ScreenShot](http://i.imgur.com/2mi2WKU.jpg)

**Comment by Hirse** [comment]
Please see https://github.com/brackets-beautify/brackets-beautify#configure-languages for the latest (2.2.0) version.
