### ISSUE TITLE
HTML attributes are added space before and after

### ISSUE THREAD

**Issue by netsi1964** [brackets-beautify/brackets-beautify#117]
I use a CMS which use tags to insert dynamic values. Those tags are based on comments. For instance:
```html
<a href="/Default.aspx?ID=<!--@Translate(products_pageid, "3")-->">
```
when I format my HTML template Beautify adds space before and after "3":
```html
<a href="/Default.aspx?ID=<!--@Translate(products_pageid, " 3 ")-->">
```
Which results in link becoming a dead link!

Are there settings where I can disable that feature? Or please fix it.

Thanks.

**Comment by Hirse** [comment]
Thanks for the detailed reports and very sorry for the delayed response.

@KavinHan, your issue seems fixed with the latest version of js-beautify.

@netsi1964, the problem is that you are not writing valid HTML. You cannot use comments inside a tag.
