### ISSUE TITLE
Make 'Beautify On Save' only apply to .html/css/js files.

### ISSUE THREAD

**Issue by CoenraadS** [brackets-beautify/brackets-beautify#132]
Hello

I would like to request that 'Beautify On Save' only applies to the files the beautifier supports.

If I'm switching between html and php files, it can be annoying to save a .php file and accidently  have the formatting ruined.

I understand this is a very minor issue, as I could disable the 'Beautify On Save' and manually beautify the relevant files, but I feel like it could be a nice enhancement.

**Comment by mfromin** [comment]
+1

**Comment by Hirse** [comment]
In the latest version (1.20) we updated the library version, so it shouldn't break PHP anymore.
In the next version, you will be able to specify the *Beautify on Save* option on a file and language level.
