### ISSUE TITLE
Problems with PHP

### ISSUE THREAD

**Issue by davidperezgar** [brackets-beautify/brackets-beautify#135]
When I "beautify" a PHP file, it changes variables and gives problems with the php file.

for Ex.
 <?php 
    $args = array(

it converts to:
<?php $args=a rray(

And puts everything in a line...

Thanks!

**Comment by netlarico** [comment]
the same problem!, it's posible to disable beautify in php files?

**Comment by bitwiseman** [comment]
Done. https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v157

**Comment by davidperezgar** [comment]
Nice bitwiseman... ;)
