### ISSUE TITLE
Problem with underscore.js template

### ISSUE THREAD

**Issue by kdureidy** [brackets-beautify/brackets-beautify#137]
Formatting the Underscore.js template code is casing errors in code and ruins the code syntax. I hope you can fix it soon.

**Comment by bitwiseman** [comment]
This is fixed in the underlying library. 
Need to update. 
https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v157

**Comment by Hirse** [comment]
Library was updated in 1.20.
