### ISSUE TITLE
"Could not determine file type" dialog

### ISSUE THREAD

**Issue by joepie91** [brackets-beautify/brackets-beautify#138]
I accidentally hit a key combination triggering Beautify, and I noticed that I got an `alert()` dialog, rather than a Brackets-styled dialog like most extensions would present.

For consistency, it would probably be better to use a Brackets-styled dialog - I'm not familiar with the extension API, but I presume there's an API call for that.

**Comment by fdecampredon** [comment]
Honestly it would be better if no alert/dialog at all would be displayed, Ctrl-alt-L is pretty much standard for beautify, and so we can't use it in other extension (like my typescript one)

**Comment by Hirse** [comment]
We are going to use a Brackets style dialog in the next version, but it might be worth to add an option not to show it any more.
