### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by Trevogre** [brackets-beautify/brackets-beautify#139]
I apologize if this is not an issue and there are some setting which I'm not aware of. I haven't located documentation yet. I just thought I would go ahead and post a coupe things here that I have notice.

When I'm in html and I beautify a small block the indentation doesn't take into account the indent of the first item. So if I have the first div 3 tabs in the remainder of the block reverts left as if it wasn't. It seems that the default behavior should be to respect the tab position of the first element when you are doing a partial beautify. Sure you can go and shift tab the rest of the stuff back where it belongs but it seems like an extra step that makes things tedious. 

I would also like an option to place tag attributes on another line. it is way more readable and "beautiful" to have your attributes lining up. Especially when using something like angular where there are more attributes than normal. 

It would also be nice if you could use this tool to reorganize your attributes based upon a user defined list. I know that is probably outside of the mission of this code and might be better as another extension, but I thought I would mention it anyway. I have wanted that for a long time but haven't pursued it. 

I would consider trying to get involved and contribute but wouldn't want to dip into pursuing anything even casually unless it was on mission.

Sorry again if I just missed some docs somewhere and have wasted anyone's time.

**Comment by andreaslarsen** [comment]
+1 for enabling options somehow

**Comment by Hirse** [comment]
@Trevogre no need to apologize.
Let's go through your list one at a time:
1. I completely agree that we should respect the indentation and I will look into it.
2. This would be functionality of the beautify library that we use and I think they do have an option for it:
  `wrap-attributes: force' (https://github.com/beautify-web/js-beautify#css--html)
3. I would like that idea, but again I feel it might be better as an enhancement of the library. Why don't you open an enhancement suggestion [there](https://github.com/beautify-web/js-beautify/issues) or even submit a PR?

Generally you can provide options by having a `.jsbeautifyrc` file in your project root.
