### ISSUE TITLE
Breaks PHP

### ISSUE THREAD

**Issue by leoland** [brackets-beautify/brackets-beautify#142]
Hey. I love beautify. but unfortunately it has the odd habit of destroying php files. it doesn't get stylistic comment blocks at all and even breaks up variable names.

**Comment by skoontastic** [comment]
I love it as well, but am seeing the same thing with php files. It's adding spaces to anything inside single quotes. So, when I type in 'text', and then save, it gets changed to 'text '.

**Comment by netlarico** [comment]
How disable beautify in PHP Files?, i want only in CSS, HTML, SCSS, etc. Thanks!

**Comment by Smus** [comment]
it make my $_GET["email"] to $_GET[" email "]m with added spaced, and <?= $email ?> to <?=$ email ?> ... :-(

**Comment by T3charmy** [comment]
Also being effected by this. Either don't parse anything between <? and ?> or, fix your parser to handle PHP as well.

**Comment by nickfmc** [comment]
Hope there is a fix for this.  Very frustrating as PHP is one thing I would love to beautify

**Comment by fabiangigler** [comment]
having the same issus with php, a fix would be appreciated!

**Comment by user501254** [comment]
Same here. Beautify makes PHP code look ugly :skull:

**Comment by drewhamlett** [comment]
Hey guys, this extension uses JSBeautify for it's beautifying.  https://github.com/beautify-web/js-beautify

I'm not sure they'll support PHP formatting any time soon, but you could definitely bring it up.

Also if there is a good JS based PHP formatter or command line application I could add it in.  Much like the way SASS was added in.

**Comment by T3charmy** [comment]
@drewhamlett I mean I'd be happy if you could just ignore anything between <?php and ?>

**Comment by CodeAmend** [comment]
I wonder if this is going to be worked on? It really is a problematic bug.

**Comment by T3charmy** [comment]
This issue was fixed on js-beautify's end, just needs the updated version of it here

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v157

**Comment by freshdesignza** [comment]
I just 'lost' thousands of lines of code due to this :( ...just thought I'd mention here.

**Comment by user501254** [comment]
There are a number of freely available online tools to do that such, as [this](http://www.cleancss.com/php-beautify/). Next time take care not to select content withing `<?php...?>` tags.

**Comment by Hirse** [comment]
Brackets Beautify 1.20 is now using js-beautify 1.5.10, so I hope this should be fixed.

**Comment by bitwiseman** [comment]
@Hirse - Thanks!
