### ISSUE TITLE
Translations / More languages

### ISSUE THREAD

**Issue by herrherrmann** [brackets-beautify/brackets-beautify#144]
There are several [pull requests](https://github.com/drewhamlett/brackets-beautify/pulls) for new translations (currently Italian, Spanish, Japanese and German) of your cool plugin - I think those are safe to accept.

Let us translators know if there's anything we're missing.
Thanks and keep up the good work!

**Comment by Hirse** [comment]
Thanks for your and all translators contributions.
We have merged most of the pull requests.

We have recently changed the used strings. It would be great if you could update your translations.
Additionally, please add a translated description to the `package.json`.
