### ISSUE TITLE
"Installation Failed. The extension encountered and error when starting up"

### ISSUE THREAD

**Issue by smokerockspunchcops** [brackets-beautify/brackets-beautify#145]
Hi I get this error when trying to install beautify via extension mnger, Amazon url, Github repo url and placing the unzip folder into my extensions appdata. I get the same error log in dev tools console each way:

GET file://[sharedWorkDrive]/UserShares/[myUserName]/AppData/Roaming/Brackets/extensions/user/brackets-beautify/settings.json.js net::ERR_FILE_NOT_FOUND
require.js:166 Uncaught Error: Script error for: settings.json
http://requirejs.org/docs/errors.html#scripterror

How can I fix this? I need to use beautify :<

Edit: We don't have a proxy

**Comment by ChaosD** [comment]
Had the same error, this solved my problem:
https://github.com/drewhamlett/brackets-beautify/issues/93#issuecomment-60377108 
I hope it helps!

**Comment by Hirse** [comment]
Please retest if this is still an issue and reopen if necessary.
