### ISSUE TITLE
ability to wildcard a folder

### ISSUE THREAD

**Issue by RoryPicko** [brackets-beautify/brackets-beautify#149]
It would be nice to be able to wildcard a folder within the options.json

if a folder is wildcarded all js within this folder is minified

--
sorry if this is the wrong place for an enhancement suggestion, I'm new to GitHub

**Comment by Hirse** [comment]
No, this is the right place for suggestions.

With the next version, you will be able to define options on file/folder level:
https://github.com/brackets-beautify/brackets-beautify#file-options-for-beautify-on-save
