### ISSUE TITLE
Adds space to CSS MS filters, causing compilation error

### ISSUE THREAD

**Issue by dalehurwitz** [brackets-beautify/brackets-beautify#152]
Space occurs after 'progid:'

    filter: progid: DXImageTransform.Microsoft.gradient(startColorstr='#ff0088cc', endColorstr='#ff0044cc', GradientType=0);

**Comment by derwaldgeist** [comment]
Seems to be the same problem as
https://github.com/drewhamlett/brackets-beautify/issues/156

**Comment by bitwiseman** [comment]
Please make sure there's a new issue filed with js-beautify for this.  Make sure you provide input, expected output, actual output.

**Comment by Hirse** [comment]
@dalehurwitz, please retest this and open an issue with the library if the problem is still there.
