### ISSUE TITLE
sass interpolation

### ISSUE THREAD

**Issue by jolugama** [brackets-beautify/brackets-beautify#157]
For example:
```css
-webkit-transition: left #{$myvariable}s ease-out 0s,
```
If i apply Beautify in brackets:
```css
-webkit-transition: left # {
	$myvariable
}
```
And so sass not compile!!!!

**Comment by Hirse** [comment]
Please [update to latest version](https://github.com/brackets-beautify/brackets-beautify#latest-release) on GitHub and have a look at [configuring languages](https://github.com/brackets-beautify/brackets-beautify#configure-languages) and [external formatters](https://github.com/brackets-beautify/brackets-beautify#external-formatters) to configure the correct beautifier for SASS.
