### ISSUE TITLE
Wrong formating for pseudo elements, removes space between expresions

### ISSUE THREAD

**Issue by romanzmykulova** [brackets-beautify/brackets-beautify#163]
There has to be space between ".class" and "::-webkit-input-placeholder", but beutifier deletes that space which makes css selector not work as expected...

this code is for placeholder formating of input element

.class ::-webkit-input-placeholder {
    color: #fff;
}
.class  :-moz-placeholder {
    color: #fff;
}
.class  ::-moz-placeholder {
    color: #fff;
}
.class  :-ms-input-placeholder {
    color: #fff;
}

**Comment by derwaldgeist** [comment]
This might be a side-effect of this fix:
https://github.com/drewhamlett/brackets-beautify/issues/156

**Comment by bitwiseman** [comment]
Please make sure there's a new issue filed with js-beautify for this.  Make sure you provide input, expected output, actual output.

**Comment by Hirse** [comment]
@romanzmykulova, please retest this and open an issue with the library if the problem is still there.
