### ISSUE TITLE
Beautify && Code Folding

### ISSUE THREAD

**Issue by iNovozhilov** [brackets-beautify/brackets-beautify#164]
Если свернуть код, а затем выполнить "Beautify", свернутый код отображается развернутым и его больше нельзя свернуть.
sprint 3 build 1.3.0-16022 (release cd0a6aae5) 
Beautify 1.1.6

**Comment by Hirse** [comment]
Please open issues in English only.

**Comment by iNovozhilov** [comment]
https://github.com/brackets-beautify/brackets-beautify/issues/182
