### ISSUE TITLE
Ctrl-Shift-L shortcut is broken

### ISSUE THREAD

**Issue by Toub** [brackets-beautify/brackets-beautify#165]
In recent versions of brackets, Ctrl-Shift-L is already used by "edit.splitSelIntoLines" command.

What about changing the default shortcut for beautify?

A workaround is to override the configuration in .config/Brackets/keymap.json

    {
        "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
        "overrides": {
            "Ctrl-Shift-L": "me.drewh.jsbeautify"
        }
    }

**Comment by Hirse** [comment]
The shortcut is going to change in the next version.
See https://github.com/brackets-beautify/brackets-beautify#usage
