### ISSUE TITLE
Extension error on Brackets 1.4.0

### ISSUE THREAD

**Issue by nlourenco** [brackets-beautify/brackets-beautify#168]
I am repeatedly getting an extension error on Brackets build 1.4.0-16380. I must "Remove" the extension and then re-install it, however it only works for the current session. When you close and re-open Brackets again, the "Extension error" returns.

**Comment by Jebedo** [comment]
+1

**Comment by kof4dream** [comment]
my mac edition has the same problem!

**Comment by CardcaptorStacey** [comment]
Doing this for me too :(

**Comment by Hirse** [comment]
Could you look into the developer tools and post any error that you get here?
