### ISSUE TITLE
Ignore patterns

### ISSUE THREAD

**Issue by SteveMcArthur** [brackets-beautify/brackets-beautify#169]
I'm using a template system (in [docpad](https://github.com/docpad/docpad)) that has metadata at the top of the file in the format: 
```
---
something: value
somethingelse: value
---
```

I'd like to get the beautifier to ignore this section and just leave it alone. I've tested this in the main.js by creating an ignore regex (```/^[\r?\n]*---\r?\n\w+:\s*\w+\s*\r?\n---\r?\n/```) and using this to remove the section from "unformattedText" and then adding it back to "formattedText".

I guess I could send my changes as a pull request, but I think it would be better if the "ignore text" was configurable (if only by editing the the settings.json file) as a an array of "ignore patterns"

**Comment by Hirse** [comment]
You can tell the formatting library to ignore a certain area using these directives:
https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only

**Comment by Hirse** [comment]
If that is not sufficient for you, please open an issue with your request on their GitHub as this clearly falls into their area.
