### ISSUE TITLE
Beautify brakes the variable alignment

### ISSUE THREAD

**Issue by iegik** [brackets-beautify/brackets-beautify#173]
Is there some option to skip breaking spaces before `=` mark?

before:
```javascript
var name        = 0,
    description = 1;
```

after:
```javascript
var name = 0,
    description = 1;
```

- Sublime [Alignment](http://wbond.net/sublime_packages/alignment)
- JetBeans [Smart tabs](https://www.jetbrains.com/webstorm/help/code-style-javascript.html#d604134e127)

**Comment by Hirse** [comment]
You can tell the formatting library to ignore a certain area using these directives:
https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only

**Comment by iegik** [comment]
This is not beautiful.

**Comment by Hirse** [comment]
I agree that it is not optimal.

But in any case this is an issue of the library, please open an issue there if you are not satisfied with the current solution.
