### ISSUE TITLE
HTML after PHP is indented

### ISSUE THREAD

**Issue by Tugzrida** [brackets-beautify/brackets-beautify#178]
Along with other problems pointed out regarding PHP beautifying(or rather beautifying around PHP), it would seem that any PHP outside of the `<head>` or `<body>` tags causes all text afterwards to be indented by one level.

**EDIT:**
Input:
```php
<?php?>
<!DOCTYPE html>

<html>
<head></head>

<body></body>
</html>
```
Output:
```php
<?php?>
    <!DOCTYPE html>

    <html>

    <head></head>

    <body></body>

    </html>
```
It doesn't seem to matter where the PHP is(inside head, body or not inside any HTML), its contents or the HTML around it . All code below the PHP is always indented by one level.

**Comment by Hirse** [comment]
Can you add an example?
Please provide unformatted code, desired result and actual result.

**Comment by mikeee324** [comment]
The desired result (in the examples above) should be something like this:  
```
<?php?>
<!DOCTYPE html>

<html>

    <head></head>

    <body></body>

</html>
```

**Comment by Hirse** [comment]
This seems to be an issue with the library that we use, see https://github.com/beautify-web/js-beautify/issues/714.

I have created a new issue with this particular problem and example, please see https://github.com/beautify-web/js-beautify/issues/826.
