### ISSUE TITLE
make brackets ignore comma-first style of authoring the JavaScript Object Literal

### ISSUE THREAD

**Issue by shardool** [brackets-beautify/brackets-beautify#179]
can we prevent beautify from changing
```js
var Person = {
firstName : 'Bob'
,lastName: 'Connor'
,homeTown:'Dairy'
};
```

to

```js
var Person = {
firstName : 'Bob',
lastName: 'Connor',
homeTown:'Dairy'
};
```

**Comment by benyscott** [comment]
Agreed with this, anyway to do it? Must be a way to change the source code ourselves?

**Comment by Hirse** [comment]
See the [`comma_first` rule](https://github.com/brackets-beautify/brackets-beautify#beautifier-options) in the latest version.
