### ISSUE TITLE
Beautify && Code Folding

### ISSUE THREAD

**Issue by iNovozhilov** [brackets-beautify/brackets-beautify#182]
If you turn code and then run "Beautify", the collapsed code appears unfolded and can no longer be minimized.(translate.yandex.ru)
sprint 5 build 1.5.0-16538 (release cf9cf4698) 
Beautify 1.2.0 (https://github.com/brackets-beautify/brackets-beautify)

**Comment by Hirse** [comment]
Thanks for the translation.
I don't think we can prevent the code from being unfolded as potentially the entire document is replaced.
However we should look into it if beautification prevents re-folding.

**Comment by iNovozhilov** [comment]
I think "Brackets" is an IPA which can show all the code and clean up the collapse so we can safely replace the text of the entire file.(translate.yandex.ru)

**Comment by iNovozhilov** [comment]
Fixed. https://github.com/brackets-beautify/brackets-beautify/pull/186
