### ISSUE TITLE
is it possible to not "beautify" a line of my code ?

### ISSUE THREAD

**Issue by guillaumebaeriswyl** [brackets-beautify/brackets-beautify#187]
Hi there,

I'm working with a minified version of a grid system into my css sheet. 
I'd like to not "beautify" it, because there is 10'000 lines of css in the framework. 

Isn't it possible to set an exception for a line ?

Thanks for answering,
Guillaume

**Comment by Hirse** [comment]
The js-beautify provides directives to ignore or preserve certain regions of code:
https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only
However this is currently only available for JavaScript. I have opened an issue there.
