### ISSUE TITLE
Upload release to Extension Registry

### ISSUE THREAD

**Issue by Hirse** [brackets-beautify/brackets-beautify#188]
@drewhamlett, could you upload the [archive](https://github.com/brackets-beautify/brackets-beautify/releases/download/v2.0.0/brackets-beautify.zip) to the [Brackets Extension Registry](https://brackets-registry.aboutweb.com/)?

**Comment by drewhamlett** [comment]
Yea, we'll need to reach out to them so we can change the url.  Last time I changed the url from drewhjava to drewhamlett I got locked out of being able to upload.

**Comment by drewhamlett** [comment]
https://github.com/adobe/brackets/issues/9816

**Comment by Hirse** [comment]
Alright, let's see what they say.
Thanks.

**Comment by Hirse** [comment]
@drewhamlett Can you try to upload it again?

**Comment by drewhamlett** [comment]
Do you want me to try the Archive in this thread?  Or zip  up master?

**Comment by Hirse** [comment]
Please use the one mentioned before for now.
