### ISSUE TITLE
Weird Beautify Style?

### ISSUE THREAD

**Issue by raulfunkie** [brackets-beautify/brackets-beautify#191]
it seems that beautify likes to add a double line before a comment, then a single line after a comment.
![screen shot 2015-12-14 at 5 38 05 pm](https://cloud.githubusercontent.com/assets/15929687/11795577/a8c4f958-a289-11e5-8e1b-5317241ffadb.png)

If this normal behaviour? and how hard is to make it like this: 
![screen shot 2015-12-14 at 5 39 30 pm](https://cloud.githubusercontent.com/assets/15929687/11795578/a8fff8f0-a289-11e5-9a83-368c9f84be82.png)

**Comment by Hirse** [comment]
That is an issue with the beautify library that we are using.

It seems like something similar is already tracked as an issue there:
https://github.com/beautify-web/js-beautify/issues/531
https://github.com/beautify-web/js-beautify/issues/645

Please open another issue with them, if you think the ones mentioned to not cover your case and link it here.
