### ISSUE TITLE
.jsbeautifyrc or .jsbeautify

### ISSUE THREAD

**Issue by klarkc** [brackets-beautify/brackets-beautify#192]
I was looking here, when you set the configuration file to .jsbeautifyrc the configuration is not loaded. When you rename to .jsbeautify, the config is loaded.

In the README.md file is saying you must use .jsbeautifyrc

Related: https://github.com/brackets-beautify/brackets-beautify/issues/151

**Comment by Hirse** [comment]
For the version you get through the Extension Registry the file has to be `.jsbeautify`, but was updated for version 2.0.0 to `.jsbeautifyrc`.
