### ISSUE TITLE
Beautifying Google Analytics Code Issue

### ISSUE THREAD

**Issue by codememobile** [brackets-beautify/brackets-beautify#194]
Hey everyone, I'm curious how everyone is doing at beautifying there code when they have a google analytics script in the bottom of there page. It "formats" it in a very odd way. I did a test version to show you guys. 

![capture](https://cloud.githubusercontent.com/assets/15266715/12622564/f694d75c-c4f3-11e5-90c4-faeaf8e66849.JPG)

Will this Hurt the code, as in will it stop working if the snippet is formatted like that?

**Comment by codememobile** [comment]
I guess you could say it's not odd, as in that is what it would look like if you did the script by hand and formatted it correctly, but will google still recognize it formatted like that?

**Comment by Hirse** [comment]
As long as you don't get syntax errors, the formatted code should be fine. Google Analytics doesn't care about how it looks, but how it works.

If you don't want that snippet beautified, you can add a [preserve comment](https://github.com/beautify-web/js-beautify#directives-to-ignore-or-preserve-sections-javascript-only):
```html
<script>
    /* beautify preserve:start */
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('send', 'pageview');
    /* beautify preserve:end */
</script>
```
(Snippet taken from [Google Developers](https://developers.google.com/analytics/devguides/collection/analyticsjs/).)

**Comment by codememobile** [comment]
Perfect! Thank you @Hirse
