### ISSUE TITLE
Extension failed to load

### ISSUE THREAD

**Issue by celticdarren** [brackets-beautify/brackets-beautify#205]
Hi all,

Getting this error in dev tools:

```
[Extension] failed to load /Users/Darren/Library/Application Support/Brackets/extensions/user/brackets-beautify-master - Error: Load timeout for modules: i18n!nls/strings_unnormalized4,i18n!nls/strings
http://requirejs.org/docs/errors.html#timeout/utils/ExtensionLoader.js:220 
errback
```

Anyone any ideas?

I've downloaded master ZIP and copied it to the usr folder in extensions and also download the jsbeautify master zip and placed it in the thirdparty folder.

No luck. Thanks.

**Comment by IgorNovozhilov** [comment]
Send us an archive folder "/Users/Darren/Library/Application Support/Brackets/extensions/user/brackets-beautify-master"

**Comment by Hirse** [comment]
The master zip of this repository should be all that is required.
We did have an error in the `package.json` for a while that might have broken the extention, but that is already fixed.

Please try to update and retest.

**Comment by jamesst20** [comment]
Samething. Unzipped brackets-beautify.zip in "/Users/James/Library/Application Support/Brackets/extensions/user/brackets-beautify" and in the Extension Manager --> Installed, it says Extension error. However, I do not know how to get the log.

**Comment by Hirse** [comment]
@jamesst20 The extension was never tested on that Editor. I am going to try, but generally we support Brackets only.

**Comment by jamesst20** [comment]
@Hirse

Thank you, however it is still Bracket in Intel XDK, probably with juste few changes

**Comment by Hirse** [comment]
If it is close to Brackets, try `F12` to open the Developer Tools which should include a console for errors.

**Comment by jamesst20** [comment]
Nothing comes up sadly. I am on OS X btw

**Comment by Hirse** [comment]
@jamesst20 I tried with Intel XDK, but I was unable to see any more information.

My best guess is that it uses an older version of Brackets than this extension supports (1.7.0).
