### ISSUE TITLE
Support beautify of Vue.js files

### ISSUE THREAD

**Issue by ErickPetru** [brackets-beautify/brackets-beautify#206]
[Vue.js](http://vuejs.org/) is a good framework for the view layer, similar in some ways to React but still much more closer to the traditional separation of concerns with HTML+CSS+JavaScript.

It uses a concept they call [Single File Components](http://vuejs.org/guide/application.html#Single-File-Components): basically one file per component with .vue extension, which inside it has a structure similar to HTML but with template, scripts and styles all there.

Please, add this support to Brackets Beautify, since it's almost the same engine that the HTML beautifier uses (with JavaScript and CSS inside its own tags of course).

**Comment by IgorNovozhilov** [comment]
only native JS! only hardcore! :smile:

**Comment by Hirse** [comment]
If this only means running `.vue` files through `html-beautify` I don't see a problem in general.

However, as our language detection only supports languages that Brackets knows (also through extensions) it will only work, if you have an extension installed that introduced the `vue` language.
