### ISSUE TITLE
Sass: Could not determine file type

### ISSUE THREAD

**Issue by slip** [brackets-beautify/brackets-beautify#207]
Whenever I try to beautify a sass document, I get this:

JavaScript Alert - file:///
Could not determine file type

Any ideas?

Thanks!

**Comment by slip** [comment]
Here is what I have found: main.js doesn't include a 'sass' case.

Just copying the 'scss' case and naming it 'sass' doesn't work, obviously. It gets rid of the js alert, but doesn't format correctly.

What I want to happen: execute 'sass-convert filename.sass filename.sass'…

I'll continue to dig around.

**Comment by tonygon** [comment]
At the end of [brackets-beautify page](http://brackets.dnbard.com/extension/brackets-beautify), section SASS, you can find the instructions for external formatters.
However, this does not work for me, maybe you'll have better luck.

**Comment by Hirse** [comment]
Please [update to latest version](https://github.com/brackets-beautify/brackets-beautify#latest-release) on GitHub and have a look at [configuring languages](https://github.com/brackets-beautify/brackets-beautify#configure-languages) and [external formatters](https://github.com/brackets-beautify/brackets-beautify#external-formatters).
