### ISSUE TITLE
switch case formatting conflicts with editor default

### ISSUE THREAD

**Issue by trevorbest** [brackets-beautify/brackets-beautify#208]
When you write a switch case block, Brackets will indent the 'case' from the 'switch' statement, but beautify aligns the 'case' with the 'switch'. It would make sense if the beautify would agree with the editor on the level of indentation.

I tried setting jslint_happy in .jsbeautifyrc to no avail.

(/home/trevor/.config/Brackets/extensions/user/brackets-beautify/thirdparty/js-beautify/js/test/resources/indent11chars/.jsbeautifyrc was the only copy I found)

**Comment by Hirse** [comment]
Please [update the extension](https://github.com/brackets-beautify/brackets-beautify#latest-release) and try again.
