### ISSUE TITLE
Nonexistent command bb.beautify.beautify

### ISSUE THREAD

**Issue by xucaen** [brackets-beautify/brackets-beautify#209]
Hi, in the documentations it says to change the shortcut add an override entry using the "bb.beautify.beautify" command. But, when I do that, I get and error saying "You are assigning shortcuts to nonexistent command" bb.beautify.beautify.

```json
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        "Alt-Shift-F": "bb.beautify.beautify"
    }
}
```

**Comment by Hirse** [comment]
Due to some trouble uploading the new version to the Brackets Registry the documentation already describes a newer version than available inside Brackets.

Please [update manually](https://github.com/brackets-beautify/brackets-beautify#latest-release) to get the newest version.
