### ISSUE TITLE
Toolbar icon to Beautify

### ISSUE THREAD

**Issue by mrleblanc101** [brackets-beautify/brackets-beautify#211]
Hi,
I would like an option to have an icon in the toolbar (on right side of the editor) to Beautify the current file.
I know there are many other option to Beautify like the keyboard shortcut or the edit menu, but coming from Animate (ex Flash pro) i often reach to the corner to auto-indent my file. Also, i think i would be good for new Brackets user.
Could you add this in the settings if you don't want to enable it by default to prevent cluttering the toolbar ?

**Comment by Hirse** [comment]
Sure, that sounds like a valid requirement.

Do you have a good idea for an icon? :wink:

**Comment by mrleblanc101** [comment]
Wow thanks for the very quick reply !
Magic wand, sparkling star, something like that.
