### ISSUE TITLE
Whitespace inside (:first-child) when it's in @media section of a css file

### ISSUE THREAD

**Issue by Rixuel** [brackets-beautify/brackets-beautify#216]
So I was working on my website menu bar and then I encounter an error and I noticed it was because of the beautify functionality.

Let's say I have this css code:
`ul.topnav li:not(:first-child) {
	display: none;
}`

Everything is fine when I beautify the code above, but if I add the code in a @media screen and (max-width:680px) section, there is a whitespace between ":" and "first-child", here an example:

Before beautify:
`@media screen and (max-width:680px) {
	ul.topnav li:not(:first-child) {
		display: none;
	}
}`

After beautify:
`@media screen and (max-width:680px) {
	ul.topnav li:not(: first-child) {
		display: none;
	}
}`

(:first-child) works and (: first-child) don't work.

**Comment by bdobry** [comment]
I encounter the same problem every time there's colon punctuation twice in the line not separated by the spacebar, for instance:`li:not(:hover)`. Beautify makes a syntax error by adding unnecessary space after second colon as you showed. Quite annoying

**Comment by bitwiseman** [comment]
This is fixed in js-beautify 1.6.4.

**Comment by Hirse** [comment]
@bitwiseman Thanks for the notice.
@Rixuel, @bdobry Please try [v2.3.0](https://github.com/brackets-beautify/brackets-beautify/releases/tag/v2.3.0) which includes an updated js-beautify library.

**Comment by Rixuel** [comment]
@Hirse Will it be downloadable directly in Bracket?

**Comment by Hirse** [comment]
@Rixuel I hope it will be eventually, but we are having issues (see the readme) with the Brackets Team regarding the ownership of the extension in the Brackets extension registry, so it doesn't look like it will be available in Brackets soon unfortunately.
