### ISSUE TITLE
Is there a way to use this on Ruby/Rails Project? with External formatters

### ISSUE THREAD

**Issue by sedhuait** [brackets-beautify/brackets-beautify#217]
Is there a way to tweak this plugin to format .rb files on ruby/rails project files like .rb, gemfile, .erb etc. I didn't find any other plugin as well which supports ruby/rails files.

**Comment by Hirse** [comment]
Yes, with the [latest version](https://github.com/brackets-beautify/brackets-beautify#latest-release) you can add [external formatters](https://github.com/brackets-beautify/brackets-beautify#external-formatters) and [configure](https://github.com/brackets-beautify/brackets-beautify#configure-languages) the languages that they support.

Please have a look at the Readme (or the links in this comment) and let us know if you have any problems.
