### ISSUE TITLE
Perl beautify Could not determine type Version 1.2.0

### ISSUE THREAD

**Issue by wyattbiker** [brackets-beautify/brackets-beautify#218]
Any ideas why I can't beautify perl but can beautify js and html?

The file extension shown is .pl

Brackets color codes properly. However I will get Could not determine Type when I right click and attempt to beautify. 

Thanks!

**Comment by Hirse** [comment]
Brackets syntax highlighting is independent of the beautification support provided by this extension.
Currently, we only support JavaScript, CSS, HTML, and languages that are similar enough to be run through the same formatter.

If you know of a JavaScript library to beautify perl, please let us know and we will work on integrating it.

If you have any program to beautify perl, you can add it as an [External Formatter](https://github.com/brackets-beautify/brackets-beautify#external-formatters) with the [latest version](https://github.com/brackets-beautify/brackets-beautify#latest-release) of this extension.
