### ISSUE TITLE
static get name get's contatenated

### ISSUE THREAD

**Issue by sielay** [brackets-beautify/brackets-beautify#220]
line `static get myField` after `cmd + L` turns into `staticget myField` version 1.2.0

**Comment by Hirse** [comment]
What language is this?

Please update to the latest version and try again.

**Comment by sielay** [comment]
Will try. That happened in JS in ES6 flavour.

**Comment by Hirse** [comment]
Thanks. If you still have issues, could you provide a larger, complete code sample?

**Comment by Hirse** [comment]
Closing as I can't reproduce it with version 2.4.0.
