### ISSUE TITLE
Whta problems

### ISSUE THREAD

**Issue by Marco105** [brackets-beautify/brackets-beautify#221]
W7 react by asking authorisation to open file in your plug so what's the matter with it?
3 days i try to run this extension...
Why there is no install by the standard extension way....

**Comment by Hirse** [comment]
I am sorry, I don't understand what you are talking about.
What is "W7"?

Regarding the installation, please see the [Readme](https://github.com/brackets-beautify/brackets-beautify#version-information) and the linked Brackets Issue.

**Comment by Marco105** [comment]
Windows seven 64 need ask security check when try open some files on the new folder, that's not happend with file come from standard install, mean installed with the extensions way.
I try further install the formatter for typescript but don't where beautifier is hosted.

**Comment by Hirse** [comment]
I have not experienced any security check with extension files before, neither my own or others I have modified, so I am unable to give more information on that.

After installing the TypeScript formatter, open the Preferences in Brackets (`Debug` > `Open Preference File`) and add the following to the bottom (or modify existing `bb.beautify.`-keys): 
```json
    "bb.beautify.beautifiers": {
        "ts": {
            "command": "/path/to/file --with args"
        }
    },
    "bb.beautify.languages": {
        "css": "css",
        "ejs": "html",
        "handlebars": "html",
        "html": "html",
        "javascript": "js",
        "json": "js",
        "less": "css",
        "php": "html",
        "scss": "css",
        "svg": "html",
        "vue": "html",
        "xml": "html",
        "typescript": "ts"
    }
```
Adopt the path/command (and perhaps the language id as I am not sure how the TypeScript id is).

**Comment by Marco105** [comment]
TSFMT installed but nothing better.
Don't know what typescript need to run...

**Comment by Marco105** [comment]
On Windows 7 64, the Brackets Beautify 2.2 not working, so I reinstall the official version from Extension Manager.

**Comment by Hirse** [comment]
For tsfmt please follow this guide:
[TypeScript Formatter(tsfmt) Setup](https://github.com/brackets-beautify/brackets-beautify/wiki/External-Formatter:-TypeScript-Formatter-(tsfmt))

If you have any other problem, please open another issue clearly describing your problem.
