### ISSUE TITLE
SVG formatting (Language configuration)

### ISSUE THREAD

**Issue by retan** [brackets-beautify/brackets-beautify#223]
I'm trying to add some custom language configuration to global user preferences (global brackets.json) but can't get it to work. I tried the set mentioned in documentation and beautify still doesn't recognize SVG.  (Windows 10 64bit pro, Brackets Release 1.7 build 1.7.0-16898 (release b0a363b71) )

This is how my brackets.json looks like:

``` json
{
    "fonts.fontSize": "15px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "healthData.healthDataTracking": false,
    "themes.theme": "dark-theme",
    "jshint.options": {
        "asi": true,
        "browser": true,
        "eqeqeq": false,
        "eqnull": true,
        "es3": true,
        "expr": true,
        "jquery": true,
        "latedef": true,
        "laxbreak": true,
        "nonbsp": true,
        "strict": true,
        "undef": true
    },
    "jshint.globals": {
        "console": true,
        "Modernizr": true,
        "JSON": true,
        "skrollr": true
    },
    "me.drewh.jsbeautify.on_save": false,
    "brackets-minifier.on-save": false,
    "dnbard.documents-toolbar.icons": true,
    "dnbard.documents-toolbar.smallIcons": false,
    "dnbard.documents-toolbar.tooltip": false,
    "dnbard.documents-toolbar.close_left": false,
    "dnbard.documents-toolbar.workingFiles": true,
    "dnbard.documents-toolbar.brackets_font": true,
    "dnbard.documents-toolbar.grayscaleIcons": false,
    "dnbard.documents-toolbar.showCloseButton": true,
    "linting.collapsed": true,
    "custom.work.showButtonForToolbar": true,
    "custom.work.horizontalBar.noSplitButton": true,
    "custom.work.hover.sidebar": true,
    "custom.work.scrollwheel": true,
    "soimon.DocumentOutliner.enabled": false,
    "livedev.multibrowser": false,
    "bb.beautify.languages": {
        "css": "css",
        "ejs": "html",
        "handlebars": "html",
        "html": "html",
        "javascript": "js",
        "json": "js",
        "less": "css",
        "php": "html",
        "scss": "css",
        "svg": "html",
        "vue": "html",
        "xml": "html"
    }
}
```

Getting an alert:
![image](https://cloud.githubusercontent.com/assets/3779428/18285623/8af2df68-746f-11e6-94a9-de5be5d78273.png)

**Comment by Hirse** [comment]
Please install the latest version (at least > 2.2.0) of Brackets Beautify. See the Readme for details of how to install.

**Comment by retan** [comment]
I've installed the lastest version but something is still wrong.
It handles regular file types (html, js, css / less) as it should. But on SVG it deos nothing. No warning, no error. I still got the the same "brackets.json" file showed in the previous post.

**Comment by Hirse** [comment]
SVG is treated as HTML by default.
If you don't have any custom languages or formatters, you can just remove the `bb.beautify.languages` block from your preferences. Make sure, that you don't have them again in your local projects `.brackets.json` preference file.

It might be that your SVG code is already beautified, you wouldn't see any notification then.
Try a minimal example in your `.svg` file like
```xml
<a>
<b />
</a>
```
and check if the middle tag gets indented.

**Comment by retan** [comment]
I've removed the `bb.beautify.languages` block from preferences and there`s nothing regarding beautify in project's `.brackets.json` file.

If tried your example and several of my own (clearly not formatted / beautified right) and ... nothing happend.

**Comment by Hirse** [comment]
@retan Can you open the Brackets Developer Tools (press F12 or use the Debug menu) and see if there are any messages when you try to beautify?

By the way, how are you triggering the beautification? Can you try different ways (Edit menu, toolbar button, keyboard shortcut)?

**Comment by retan** [comment]
@Hirse  I've don that. Nothing regarding beautify in Console.
It's the same with different triggering methods but now that I tried it on completely different file than before, I'd noticed fact it does something but not what it should.

This is the input (I've simplified it and messed the indentation intentionally; it was the same with the original / full markup)
```svg
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 36 36" style="enable-background:new 0 0 36 36;" xml:space="preserve">
                    <rect id="XMLID_20_" x="-7" 
                          class="st0" 
                          width="49" height="36"/>
</svg>


```
The output
```svg
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 36 36" style="enable-background:new 0 0 36 36;" xml:space="preserve">
                    <rect id="XMLID_20_" x="-7" 
                          class="st0" 
                          width="49" height="36"/>
</svg>
```
... it just removed a line break in the opening `<svg>` tag. :laughing:

**Comment by Hirse** [comment]
@retan I could reproduce the output you posted.
This seems to be a problem with the js-beautify library. Could you open another issue with them including your sample?

**Comment by retan** [comment]
I've done that. See: https://github.com/beautify-web/js-beautify/issues/1027

**Comment by Hirse** [comment]
@retan Thanks. Will follow that issue.

**Comment by schroef** [comment]
Question about adding languages, i can not fond a language file anywhere in the folders nor in the settings. I would like to add python as language and have some settings already.

**Comment by retan** [comment]
@schroef Language file? If you mean a file, where you put the language options mentioned above, then see: https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences

**Comment by schroef** [comment]
i mean for checking the code, i tried adding py script to that default default.jsbeautifyrc file but that didnt work

**Comment by Hirse** [comment]
@schroef Please don't comment about your python problem here. Use the issue you created (#231).
