### ISSUE TITLE
Doesn't work when i also use minifier.

### ISSUE THREAD

**Issue by gruntek** [brackets-beautify/brackets-beautify#225]
It stopped work after i installed minifier. It crashes while brackets is trying to load extensions on start. When i delete the minifier extension then beautify works again.

Is there a way to fix that issue?
I don't know what else information you need to solve that problem,

**Comment by Hirse** [comment]
Please provide the version of Brackets, the version of this extension, and a link to the "minifier extension" you have installed.

**Comment by gruntek** [comment]
Brackets 1.7 on windows 10
Brackets Beautify 2.x using js-beautify version 1.6.4
Link to minifier - [https://github.com/wylst/brackets-minifier](https://github.com/wylst/brackets-minifier)

**Comment by Hirse** [comment]
That extension seems to be out of maintenance. Have you tried the linked [fork](https://github.com/abagshaw/brackets-minifier)?

Are you using the minify-on-save feature?

**Comment by gruntek** [comment]
OMG, I'm so sorry that I took Your time instead read carefully :/

Of course that linked fork works perfectly.

Sorry again and thank You for help!

**Comment by Hirse** [comment]
No problem. Just happy this is not my fault. 😉
