### ISSUE TITLE
Beautify command-shift-L no longer working (Brackets 1.7)

### ISSUE THREAD

**Issue by jaschanarveson** [brackets-beautify/brackets-beautify#227]
The title pretty much says it all - I installed the latest Beautify just now (2.3) and still no go.

Is this happening to anyone else?

Mac | OS 10.11.6 | Brackets 1.7 | Beautify 2.3

**Comment by GoliafRS** [comment]
`Ctrl + Alt + B` new keybind...

**Comment by Hirse** [comment]
Please see the readme: https://github.com/brackets-beautify/brackets-beautify#user-key-map-for-beautify
