### ISSUE TITLE
Middleman .html.erb support

### ISSUE THREAD

**Issue by mkals** [brackets-beautify/brackets-beautify#228]
I have made a .jsbeautifyrc file in the root of my project with the following contents: 

```
{
    "bb.beautify.languages": {
        "erb": "html",
        "html.erb": "html"
    }
}
```

Beautify still responds with "this language is unsupported" when I try running it on a ".html.erb" file. I am running Beautify 2.3.0. Any suggestions as to what I am doing wrong?

**Comment by Hirse** [comment]
The key is the Brackets language id, not the file ending.

**Comment by mkals** [comment]
Thank you for your quick reply! The contents of the files I am attempting to beautify is HTML. I wish the extension to treat ".html.erb" files as though they were normal ".html" files. Do you have a suggestion as to how this could be achieved?

**Comment by Hirse** [comment]
For the extension to treat `.html.erb` files as HTML you have to provide a mapping in the _Brackets Preferences_ file similar to your original example:
```json
{
    "bb.beautify.languages": {
        "css": "css",
        "ejs": "html",
        "handlebars": "html",
        "html": "html",
        "javascript": "js",
        "json": "js",
        "less": "css",
        "php": "html",
        "scss": "css",
        "svg": "html",
        "vue": "html",
        "xml": "html",

        "erb_html": "html"
    }
}
```
Note, that you need to include the built-in mappings as any missing mappings will be removed.


What I meant with `key` is that the property name in the JSON object has to be the language id that Brackets assigns to the file.
You can get the language id by running the following in the Develop Tools (open with `F12` or _Debug_ menu) while you have the file opened:
```js
brackets.getModule('document/DocumentManager').getCurrentDocument().getLanguage().getId()
```

**Comment by mkals** [comment]
Thank you for a great reply! That improved my understanding and resolved my issue.
