### ISSUE TITLE
External Formatter: TypeScript Formatter (tsfmt)

### ISSUE THREAD

**Issue by petercz1** [brackets-beautify/brackets-beautify#230]
Superb plugin, now trying to get tsfmt to work but it doesn't:

1) works on the command line: tsfmt -r file.ts (and the changes show up in Brackets)
2) snapshot of brackets.json (I tried with and without the -r switch):

```
    "brackets-icons.iconset": "ionicons",
    "bb.beautify.beautifiers": {
          "tsfmt": {
              "command": "tsfmt -r"
          }
      },
    "bb.beautify.languages": {
        "css": "css",
        "ejs": "html",
        "handlebars": "html",
        "html": "html",
        "javascript": "js",
        "json": "js",
        "less": "css",
        "php": "html",
        "scss": "css",
        "svg": "html",
        "vue": "html",
        "xml": "html",
        "typescript": "tsfmt"
    },
    "interactive-linter.javascript": [
        "jshint"
    ],
```
3. typescript plugin is working (Martin Zagora):

https://github.com/zaggino/brackets-typescript

4. Brackets version 1.8.0

5. Brackets beautify version 2.3.0

6. Brackets beautify works on js and html

7. restarted brackets - no luck :(

This would be awesome to get working - am I doing something stupid?

PC

**Comment by Hirse** [comment]
@petercz1 this looks about right.
Could you open the Brackets Developer Tools and see if there are any errors in the console?

**Comment by petercz1** [comment]
Hi Jan,

Ok, when I open the dev console I see this error:

`Cannot assign Ctrl-Alt-B to bb.beautify.beautify. It is already assigned to bb.beautify.beautify ErrorNotification.js:122`

but my keymap looks like this:
```
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        
    }
}
```

Then when I try ctrl-alt-b (which does work for other languages) I get this error (also the same error without the -r flag set):

```
Object {killed: false, code: 127, signal: null, cmd: "tsfmt -r /home/pc/data/sites/technology/angular2/test1/src/ts.ts"} ErrorNotification.js:122
window.console.error ErrorNotification.js:122
(anonymous function) main.js:159
(anonymous function) beautify.js:17
j thirdparty.min.js:19
k.fireWith thirdparty.min.js:19
NodeConnection._receive
```
Does that help?

**Comment by petercz1** [comment]
Ok Jan,

Progress, of a sort. The error code 127 is a bash error (I think), meaning the file can't be found. I tried pasting the absolute path in for tsfmt, still the same error.

I installed a shell extension (Brackets shell) and ran echo $PATH - no path to my tsfmt! I opened a shell and checked, the correct path is in there, so I fired up brackets from the cli, tried beautify and hey presto it worked.

So I guess I need to figure out why my brackets is not picking up the $PATH variable...

PC

**Comment by Hirse** [comment]
So, shell commands inside Brackets don't get the correct `$PATH` information?
I'll have to check that myself.

@zaggino Do you know anything about problems with `$PATH` in Brackets node domains by chance?

**Comment by zaggino** [comment]
Hi, no I don't from my head. Is it just the tsfmt missing or is $PATH completely different?

**Comment by petercz1** [comment]
@zaggino Hi, the path is different ie I'm missing /home/<user>/.linuxbrew/bin/tsfmt when I check within brackets.

I'm suspecting it's a problem with my setup, although this is a fresh installation of Ubuntu 16.10 as of about five days ago.

I've checked .bash_profile etc - no luck so far. I'm trying to figure out where brackets get's it's path info from.

It's working if I fire up brackets from within a bash shell ie with the correct path set that way, so no big deal. I'm just one of those awkward coders who won't give up until somethings nailed...

If no-one else see the problem then assume it's just me! Want to close this?

PC

**Comment by zaggino** [comment]
My knowledge of Brackets on Linux is very limited, but you might wanna try Electron build (https://github.com/zaggino/brackets-electron/releases), it works a bit better on Linux than current outdated CEF shell. It might (and might not) fix this.

**Comment by petercz1** [comment]
Nope - just tried the electron build (but an interesting tip anyway!), same problem.

I've done some more testing, and I kinda think it's a path issue with my rig. I'll close this but if I solve it I'll report back.

At least we know what error code 127 is...

PC

**Comment by Hirse** [comment]
Thanks for your effort @zaggino.
Hope you find a solution @petercz1.

**Comment by zero298** [comment]
If anyone comes across a similar issue to this while using Brackets on macOS, the TypeScript guide works, but similar to the issue that everyone else is running into, the `tsfmt` command won't be in your `$PATH` unless you launch Brackets from the command line.  You can make that possible by using `File -> Install Command Line Shortcut`.

I was able to use the TypeScript formatter fine after that.

**Comment by Hirse** [comment]
@zero298 Thanks for the hint.

I cannot see that entry in the file menu. Is that menu item mac specific?
Could you post a screenshot, then I could add it to the guide.

**Comment by zero298** [comment]
@Hirse Yep, here you go:

<img width="651" alt="brackets-install_cli_shortcut_menuitem" src="https://user-images.githubusercontent.com/325543/32203770-6a244946-bdb3-11e7-80f5-09d57dcdd737.png">

**Comment by muppetjones** [comment]
As a side note, you should be able to add the absolute path to the binary instead of starting it from the command line.
