### ISSUE TITLE
Support for typescript

### ISSUE THREAD

**Issue by gerlstar** [brackets-beautify/brackets-beautify#232]
Currently there's no support for typescript formatting? When I try to Beautify, I get "Could not determine file type"

**Comment by Hirse** [comment]
No, it does not include TypeScript support by default.
For details on how to configure tsfmt as external formatter for TypeScript, see the [Wiki](https://github.com/brackets-beautify/brackets-beautify/wiki/External-Formatter:-TypeScript-Formatter-(tsfmt)).
