### ISSUE TITLE
Preserve any code inline or preserve small objects inline

### ISSUE THREAD

**Issue by chengtie** [brackets-beautify/brackets-beautify#233]
At present, the beautifier of brackets turns the following code

    opt = $.extend({ handle: "", cursor: "ew-resize", min: 10}, opt);

to

    opt = $.extend({
      handle: "",
      cursor: "ew-resize",
      min: 10
    }, opt);

Actually, I don't want the beautifier to add the newlines; the beautifier could well leave the line as it is.

Either we could let the beautifier not add newlines for any code, or we let it preserve small objects inline (see [this issue](https://github.com/beautify-web/js-beautify/issues/995)). Does anyone know if any of these solutions has been implemented?

Thanks

**Comment by Hirse** [comment]
Could you please add information about which version of the Extension you are using?
If it is not the latest, please try that one.

**Comment by Hirse** [comment]
This extension uses the latest version of the library.
Without further information, I am closing this issue.
