### ISSUE TITLE
Beautify JSX

### ISSUE THREAD

**Issue by Tha1der** [brackets-beautify/brackets-beautify#234]
Enhancement / Feature request, to include formatting for JSX, with how popular React is, this would be really helpful.

**Comment by Hirse** [comment]
You can add support yourself by configuring jsx to use for example the js formatter:
https://github.com/brackets-beautify/brackets-beautify#configure-languages

Add the following configuration to your settings file:
```json
{
    "bb.beautify.languages": {
        "css": "css",
        "ejs": "html",
        "handlebars": "html",
        "html": "html",
        "javascript": "js",
        "json": "js",
        "less": "css",
        "php": "html",
        "scss": "css",
        "svg": "html",
        "vue": "html",
        "xml": "html",

        "jsx": "js"
    }
}
```
(This is assuming the language id for JSX is `jsx` as I can't check right now.)

**Comment by Tha1der** [comment]
Thank you for making this addition in your latest commit.
