### ISSUE TITLE
Beautify options don't work

### ISSUE THREAD

**Issue by MasterYushi** [brackets-beautify/brackets-beautify#238]
I made a `.jsbeautifyrc` file in the root folder of my project as you can see and specified some options:

![image](https://cloud.githubusercontent.com/assets/24858182/24246901/6bf090a8-0fef-11e7-8429-45b5604c3337.png)

`indent_inner_html=true` should indent `head` and `body` and `preserve_newline=false` should remove trailing new lines as far as I know but both of these do not seem to work:

![image](https://cloud.githubusercontent.com/assets/24858182/24247045/07a9ba9c-0ff0-11e7-842e-6ede74683223.png)

With these options enabled, the circled whitespace should disappear and the highlighted body tag should be indented but that doesn't happen when I beautify.

**Comment by Hirse** [comment]
Your file is called `options.jsbeautifyrc` not `.jsbeautifyrc` as it should be.
