### ISSUE TITLE
Brackets extension does not seem to be working for me.

### ISSUE THREAD

**Issue by GusGF** [brackets-beautify/brackets-beautify#240]
What am I doing wrong here? Have written the following code in Brackets and when I try to use Beautify extension it doesn't seem to be able to format the html, see html code below.

```html
<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <title>This is a test page</title>
    <link rel="stylesheet" href="styles/Test.css">
</head>

<body>
    <p class="bluetext">The BBC has <strong>bold text</strong> its cookie <i>italic policy</i>. We use <mark>marked cookies</mark> to <small>small text ensure</small> that we give you the best <del>experience</del> on our website. This <sub>subscript includes cookies</sub> from <sup>super third party</sup> social <ins>media websites</ins></p>
    <textarea rows="7" cols="70">The BBC has <strong>bold text</strong> its cookie <i>italic policy</i>. We use <mark>marked cookies</mark> to <small>small text ensure</small> that we give you the best <del>experience</del> on our website. This <sub>subscript includes cookies</sub> from <sup>super third party</sup> social <ins>media websites</ins></textarea>
    <select>
<optgroup label="Dark colours">
    <option value="blue">blue</option>
    <option value="brown">brown</option>
</optgroup>
<optgroup label="Light colours">
    <option value="white">white</option>
    <option value="orange">orange</option>
</optgroup>
    </select>
</body>

</html>
```

**Comment by GusGF** [comment]
`<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <title>This is a test page</title>
    <link rel="stylesheet" href="styles/Test.css">
</head>

<body>
    <p class="bluetext">The BBC has <strong>bold text</strong> its cookie <i>italic policy</i>. We use <mark>marked cookies</mark> to <small>small text ensure</small> that we give you the best <del>experience</del> on our website. This <sub>subscript includes cookies</sub> from <sup>super third party</sup> social <ins>media websites</ins></p>
    <textarea rows="7" cols="70">The BBC has <strong>bold text</strong> its cookie <i>italic policy</i>. We use <mark>marked cookies</mark> to <small>small text ensure</small> that we give you the best <del>experience</del> on our website. This <sub>subscript includes cookies</sub> from <sup>super third party</sup> social <ins>media websites</ins></textarea>
    <select>
<optgroup label="Dark colours">
    <option value="blue">blue</option>
    <option value="brown">brown</option>
</optgroup>
<optgroup label="Light colours">
    <option value="white">white</option>
    <option value="orange">orange</option>
</optgroup>
    </select>
</body>

</html>
`

**Comment by Hirse** [comment]
You can use ` ``` ` to specify code blocks. (I have edited the original comment accordingly.)

Please include information how you would like it to be formatted as well as how it is formatted right now.

**Comment by GusGF** [comment]
Thanks Hirse, when I clicked on the insert code button it puts what isn't but looks like 2 single quotes!! Not the 3 you've put.

``
!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <title>This is a test page</title>
    <link rel="stylesheet" href="styles/Test.css"> </head>

<body>
    <p class="bluetext">The BBC has <strong>bold text</strong> its cookie <i>italic policy</i>. We use
        <mark>marked cookies</mark> to <small>small text ensure</small> that we give you the best <del>experience</del> on our website. This <sub>subscript includes cookies</sub> from <sup>super third party</sup> social <ins>media websites</ins></p>
    <input type="submit" value="true" /> </body>

</html>
``
