### ISSUE TITLE
JSON output not what was expected

### ISSUE THREAD

**Issue by hulu1522** [brackets-beautify/brackets-beautify#245]
I opened a ticket with jsbeatuify but it seems to have been fixed on their side so there may be an out of date module version.

https://github.com/beautify-web/js-beautify/issues/1183

The JSON formatting is coming out weird and gets hard to read when it comes to the alignment of arrays.  Normally the array would close lined up with the beginning key but after running this it formats them farther back then expected.  Here is an example of what I mean:

#### Current output:
```json
{
    "default_attributes": {
        "system": {
            "packages": {
                "install": [
          "iftop",
          "mc",
          "ngrep",
          "htop"
        ]
            }
        }
    }
}
```

#### Expected output:
```json
{
    "default_attributes": {
        "system": {
            "packages": {
                "install": [
                    "iftop",
                    "mc",
                    "ngrep",
                    "htop"
                ]
            }
        }
    }
}
```

**Comment by Hirse** [comment]
Yes, the published release of the extension is one path version behind, but the fix in that version is not related to this.

This is a matter of the [options](https://github.com/brackets-beautify/brackets-beautify#beautifier-options):
With `"keep_array_indentation": true`, it is formatted as expected.
