### ISSUE TITLE
Does not work on Brackets-Electron

### ISSUE THREAD

**Issue by tatsujb** [brackets-beautify/brackets-beautify#246]
for some reason this extension refuses to work on brackets-electron which unfortunately is basically go-to on linux since too many dependencies of normal brackets are deprecated and most of the plugin library does not work there.

why is it broken under brackets-electron and can I fix this myself?

thanks

**Comment by Hirse** [comment]
In [version 2.0.0](https://github.com/brackets-beautify/brackets-beautify/blob/master/CHANGELOG.md#200---2015-11-24) we introduced a fix when LiveDevelopment is active.
Brackets-Electron [doesn't have support for LiveDevelopment (yet)](https://github.com/zaggino/brackets-electron/issues/25) and [rejects extension that require those files](https://github.com/zaggino/brackets-electron/issues/77). 

The solution would probably be to only require those files conditionally, but I am not sure how the condition would look like.

**Comment by Hirse** [comment]
@tatsujb Feel free to checkout the `master` branch and see if this fix helps. I would appreciate any feedback.

**Comment by tatsujb** [comment]
![image](https://cloud.githubusercontent.com/assets/5132359/25499279/35a16e0c-2b8b-11e7-927c-24f35af3c458.png)
this is what I'm doing and I'm not sure it's correct (and drag and dropping the zip doesn't work under linux ) but I get "Installation Failed - Unknown internal error".

I've tried it again but no matter what I do https://github.com/adobe/brackets/issues/12380 i can only install "any template" on brackets electron and "beautify" on brackets :(

**Comment by Hirse** [comment]
Please try this URL:
`https://github.com/brackets-beautify/brackets-beautify/archive/master.zip`

**Comment by tatsujb** [comment]
that worked!
