### ISSUE TITLE
CSS beautify bug

### ISSUE THREAD

**Issue by Ahmed-ShawkyEgy** [brackets-beautify/brackets-beautify#249]
Hi,
There is this annoying bug where when I beautify a css file, hundreds of empty lines are added between blocks of code. I'd have to remove these lines manually which turns out to be a cumbersome job.
I've also noticed that this bug occurs when there are comments above the blocks of code that are indented.

**Comment by Hirse** [comment]
Could you please try the latest version?

**Comment by Ahmed-ShawkyEgy** [comment]
It's working now thanks !! 
sorry for the late reply 
by the way is there any support for blade template language ?

**Comment by Hirse** [comment]
Great.

No, only HTML, JS, and CSS so far.
