### ISSUE TITLE
Bug when we write after selector while beauty on save is on

### ISSUE THREAD

**Issue by natarajnattu** [brackets-beautify/brackets-beautify#253]
when my css page is starting like this, if we put space in first line " ::-webkit-scrollbar" and try to save when beautify is on, the code is moving towards and right side of the editor and causing restart the brackets:

app.css
there is one space infront of ::-webkit-scrollbar {}.
```
 ::-webkit-scrollbar {}

```

**Comment by Hirse** [comment]
Please try with the latest version.
I was able to reproduce this with 2.4.1, but not 2.5.0.
