### ISSUE TITLE
Make the macOS note its own Wiki page

### ISSUE THREAD

**Issue by zero298** [brackets-beautify/brackets-beautify#256]
I mentioned on #230 that you have to launch Brackets from shell to have brackets-beautify be able to utilize formatters on `$PATH`.  This isn't necessarily exclusive to `tsfmt` formatter.  I'd like to make an additional Wiki page that details the issue and the fix rather than putting it only on the `tsfmt` guide since I am running into the same issue after trying to use [`gofmt`](https://golang.org/cmd/gofmt/) as well as [`clang-format`](https://clang.llvm.org/docs/ClangFormat.html).

Additionally, I believe that this will also be an issue on the Linux version of Brackets.  I'm going to double check later this evening.  If it is an issue there, I'd like to add instructions for that platform as well if they aren't the same.

Additionally, and if this should be a separate question issue I can open it as such, should I just keep adding Wiki pages for each formatter that I try?  I made the [External Formatter: Go Formatter (gofmt)](https://github.com/brackets-beautify/brackets-beautify/wiki/External-Formatter:-Go-Formatter-(gofmt)) page because I was having issues with getting everything set up and thought it might be helpful.  `clang-format` was much easier, so I'm wondering if it should get a page too.

**Comment by Hirse** [comment]
Thanks for creating more pages. 👍 

Yes, please add pages for all formatters that you try (as long as you don't mind the effort).
Also feel free to extract the macOS specific setup to its own page. (Same goes for Linux.)

As a personal note, I never used any of the external formatters, so I really enjoy the confirmation that that feature is being used. If you have any other issues with it that can not be solved by existing configuration, let me know.

Finally, please close this issue once you are done with your Wiki edits and thanks a lot.

**Comment by zero298** [comment]
OK, I went ahead and:

- Moved the macOS issue to [its own section](https://github.com/brackets-beautify/brackets-beautify/wiki/Formatters-on-$PATH) with an explanation of what was happening
- Added a platform specific issues section on the [Home wiki page](https://github.com/brackets-beautify/brackets-beautify/wiki)
- Added the [ClangFormat](https://github.com/brackets-beautify/brackets-beautify/wiki/External-Formatter:-ClangFormat-for-C,-Cpp,-Java,-JavaScript,-Objective-C,-and-Protobuf) wiki page
- Tested for the same issue on Brackets for Ubuntu, but didn't run into the issue

I'll add any more things that I run into as separate issues.  Thanks again for this great tool!
