### ISSUE TITLE
Leave HTML comments next to closing tags!

### ISSUE THREAD

**Issue by WebDevBooster** [brackets-beautify/brackets-beautify#257]
**Details about your environment:**
* Brackets Version: 1.11
* Brackets Beautify Version: 2.5.1

I prefer to have HTML comments next to closing tags like this: 
```html
</div><!-- container -->
```

Beautify puts those comments onto separate lines like this:
```html
</div>
<!-- container -->
```

How/where can I fix this unwanted behavior to leave the comments next to the closing HTML tags?

**Comment by WebDevBooster** [comment]
Hmmm... I just realized that I have this version installed: 
https://github.com/Hirse/brackets-beautify

**Comment by WebDevBooster** [comment]
OK, I've just removed the older version and installed Beautify v.2.5.1 but the issue still exists. 

The separation of the closing HTML tag and the corresponding comment onto 2 separate lines is undesired. How/where can I fix that?

**Comment by mmman64** [comment]
+1 this is annoying

**Comment by Hirse** [comment]
This is an issue in the formatting library (see https://github.com/beautify-web/js-beautify/issues/1337), you could fix it there by contributing. 😉
