### ISSUE TITLE
Is it possible not to"beautify" grid-template-areas in css code ?

### ISSUE THREAD

**Issue by ipeanuts07** [brackets-beautify/brackets-beautify#259]
Hi there,
Grid system is becoming increasingly common in css layout，many lines of template-areas are organized into one line.
Isn't it possible to set an exception for this ?

**Details about your environment:**
* Brackets Version: latest (release d3b783b99) 
* Brackets Beautify Version: latest 2.5.1

Thanks for answering.

**Comment by Hirse** [comment]
This would be something handled by the js-beautify library. Unfortunately, they do not yet have that feature in CSS, but I had opened an issue before: https://github.com/beautify-web/js-beautify/issues/813

(Also, duplicate of https://github.com/brackets-beautify/brackets-beautify/issues/187)

**Comment by bitwiseman** [comment]
@ipeanuts07 - css now supports ignoring sections. see https://github.com/beautify-web/js-beautify#ignore-directive
