### ISSUE TITLE
Mapping Nunjucks (njk) to HTML

### ISSUE THREAD

**Issue by nloprimary** [brackets-beautify/brackets-beautify#260]
I am not getting Nunjucks support despite changing:

**defaultPreferences.json**
```
	// Beautifier-Language-Mapping, see https://github.com/brackets-beautify/brackets-beautify#configure-languages

	"bb.beautify.languages": {
                // Default: html
		"njk": "html"
	}
```

**brackets.json**
```
{
    "bb.beautify.languages": {"njk": "html"}
}
```

**Details about your environment:**
* Brackets Version: Release 1.12 build 1.12.0-17621 (release d3b783b99) 
* Brackets Beautify Version: 2.5.1

**Comment by Hirse** [comment]
You are changing the correct settings, but the language id is incorrect.
The language id is (technically) independent of the file extension and depends on the language mode set by the extension adding the support for the language.
Assuming you are using [nunjucks-brackets](https://github.com/axelboc/nunjucks-brackets), it works with these settings:
```json
{
    "bb.beautify.languages": {
        "nunjucks": "html"
    }
}
```
