### ISSUE TITLE
not beautifying certain tags in html

### ISSUE THREAD

**Issue by wodash** [brackets-beautify/brackets-beautify#263]
**Details about your environment:**
* Brackets Version: Release 1.12 build 1.12.0-17621 
* Brackets Beautify Version: 2.5.1

Issue: when trying to beautify (and beautify on save), certain tags like `<svg>` and `<option>` are not getting formatted.

**Comment by Hirse** [comment]
Can you please add an example how they are formatted currently and how you would like them to be formatted?

**Comment by Hirse** [comment]
Assuming related issue: https://github.com/beautify-web/js-beautify/issues/1383
