### ISSUE TITLE
HTML inside JS in an HTML document break when formatted during Live Preview

### ISSUE THREAD

**Issue by CryptoVaraan** [brackets-beautify/brackets-beautify#277]
**Details about your environment:**
* Brackets Version:  Release 1.13 build 1.13.1-17699 (windows-release-1.13.1 fc2ebbeea) 
build timestamp: Mon Dec 03 2018 09:26:27 GMT+0000
* Brackets Beautify Version: 2.7.0

The function function updateOutput() gets destroyed (original line 154) when Beautified..
The line is ripped apart and broken after that.
[working-page-9-4.15.zip](https://github.com/brackets-beautify/brackets-beautify/files/2963728/working-page-9-4.15.zip)

**Comment by Hirse** [comment]
I cannot see any issue with the beautification of the given code.

Please post the exact code before and after you beautify.

**Comment by CodeLucifer** [comment]
有没有确切的代码？

**Comment by CryptoVaraan** [comment]
With the given file you should select the text of the complete function updateOutput, lines 152 up to and including 160, then hit the Beautify button. The result is in the file attached to this post.
[working-page-9-4.15_AFTER.zip](https://github.com/brackets-beautify/brackets-beautify/files/2965724/working-page-9-4.15_AFTER.zip)

**Comment by CryptoVaraan** [comment]
I'm not sure if it is of any help, but, if i'm using the plugin https://github.com/HookyQR/VSCodeBeautify in VSCode, on the same file, then it works good. It is reformatted and kept intact. I think these plugins both use the same underlying code...

**Comment by CodeLucifer** [comment]
感谢您的帮助

**Comment by bitwiseman** [comment]
@CryptoVaraan 
Please post your input, expected output, and actual output in this issue, like this (only an example):

Input:
```
//This is some js
var a =1;
```

Expected output:
```
//This is some js
var a=1;
```

Actual output:
```
//This is some js
var a = 1;
```

**Comment by CryptoVaraan** [comment]
I added the jquery-min.js dependency to the attached zip file. If you input the files to brackets and run the ...BEFORE, you can see the result/intention of the code. If you try to run the ...AFTER it will generate an error in the Chrome console and stops working for that reason. The formatted code looks good, but does not work. This problem is best demonstrated by reproducing it...

Input is:
~~~JS
            function updateOutput() {
                
                $("iframe").contents().find("html").html("<html><head><style type='text/css'>" + $("#cssPanel").val() + "</style></head><body>" + $("#htmlPanel").val() + "</body></html>");
                
                document.getElementById("outputPanel").contentWindow.eval($("#javascriptPanel").val());
                
                
                
            }
~~~

Actual output:
~~~JS
           function updateOutput() {

            $("iframe").contents().find("html").html("<html>

            <head>
                <style type='text/css'>
                    " + $("#cssPanel").val() + "
                </style>
            </head>

            <body>" + $("#htmlPanel").val() + "</body>

            </html>");

            document.getElementById("outputPanel").contentWindow.eval($("#javascriptPanel").val());



            }            
~~~

Expected output is:

~~~JS
 Console.log("It still works after Beautifying !");
~~~

**Comment by Hirse** [comment]
Thanks for the help @bitwiseman. This is an issue on my side related to the live debugging feature of Brackets.

When running the live session, any change to the top `<html>`-tag causes weird duplication issues. I have added a work-around, which breaks in this case because this is an HTML-document, but some `<html>` is inside a JavaScript section of it.

While I am working to fix this, @CryptoVaraan I would recommend to split HTML, CSS, and JS into separate files in your project. That would mitigate this issue and give you in general better editor support for each individual language.

**Comment by Hirse** [comment]
I have published a fix.
Please update to the latest version.

**Comment by CryptoVaraan** [comment]
@Hirse Thanks, i know that it is good practice to split the files and keep all stuff separate, but these files are part of an online course and are provided as-is (not my style of programming :) I will test it again and provide feedback when applicable...
