### ISSUE TITLE
php variable inside a js script is being formatted

### ISSUE THREAD

**Issue by Icaras12x** [brackets-beautify/brackets-beautify#284]
`<script>var test = <?php echo "hello"; ?>;</script>` 
This is getting formatted this way:
`<script>var test = < ? php echo "hello"; ? > ;</script>` 
Adding extra spaces that disable php code from functioning.

**Comment by Hirse** [comment]
This is an issue with the limited PHP support of the js-beautify library we are using. Could you please open an issue [there](https://github.com/beautify-web/js-beautify/issues)?

**Comment by bitwiseman** [comment]
Actually, no sorry.  
In 1.9.0 we improved the processing of templating languages such as php and turned them on by default.  Unfortunately, that causes issues for some users who were no using templating (See https://github.com/beautify-web/js-beautify/issues/1647 for details).
 
So, there is a new setting added in 1.10.0: `templating`.  
```
values: (auto,django,erb,handlebars,php) [default: "auto"] auto = none in JavaScript, all in html
```
Even though this is html, the area inside the script is treated as Javascript and so by default does not handle php.  To fix this, set `"templating": "php"` (in your `.jsbeautifyrc` file).

**Comment by Hirse** [comment]
Wow, that sounds great. Thanks, @bitwiseman.

**Comment by Hirse** [comment]
I have published a [new version](https://github.com/brackets-beautify/brackets-beautify/releases/tag/v2.9.1) that set the templating setting based on the document language so it should work for php without changing anything.
