### ISSUE TITLE
Can't beautify php

### ISSUE THREAD

**Issue by ds85snow** [brackets-beautify/brackets-beautify#289]
Win10 using https://github.com/brackets-beautify/brackets-beautify

I have changed prefs to include
```
"php": {
    "enablePhpTooling": false
},
"bb.beautify.languages": {
    "css": "css",
    "ejs": "html",
    "handlebars": "html",
    "html": "html",
    "javascript": "js",
    "json": "js",
    "jsx": "js",
    "less": "css",
    "php": "html",
    "scss": "css",
    "svg": "html",
    "vue": "html",
    "xml": "html"
}
```
I don't need php tools, as I'm only doing light editing, so I don't have wamp installed.

Beautify works on other files, but does nothing in php.

**Comment by Hirse** [comment]
PHP should be enabled by default, but only the HTML parts of it get beautified with the standard tools.
If your file is only PHP (without HTML tags) it will not change anything.

Could you share some example code to better understand you situation please?

**Comment by ds85snow** [comment]
I see, I hoped it would reindent, and clean braces like it does with css

`add_action('litespeed_esi_shortcode-vc_media_grid', 'enqueue_vc_assets');

function enqueue_vc_assets() {
	error_log('enqueue_vc_assets');
	if (function_exists('vc_asset_url')) {
		wp_register_style( 'flexslider', vc_asset_url( 'lib/bower/flexslider/flexslider.min.css' ), array(), WPB_VC_VERSION );
		wp_register_style( 'vc_pageable_owl-carousel-css', vc_asset_url( 'lib/owl-carousel2-dist/assets/owl.min.css' ), array(), WPB_VC_VERSION );
		wp_register_style( 'animate-css', vc_asset_url( 'lib/bower/animate-css/animate.min.css' ), array(), WPB_VC_VERSION );
		wp_register_style( 'prettyphoto', vc_asset_url( 'lib/prettyphoto/css/prettyPhoto.min.css' ), array(), WPB_VC_VERSION );
`

**Comment by Hirse** [comment]
No, sorry, PHP is not supported by the formatting library that we use ([js-beautify](https://github.com/beautify-web/js-beautify)), but you can hook up an [external formatter](https://github.com/brackets-beautify/brackets-beautify#external-formatters) if you have one for PHP.
