### ISSUE TITLE
Extra space added in nullish coalescing operator (??) for javascript

### ISSUE THREAD

**Issue by DylanTim** [brackets-beautify/brackets-beautify#299]
**Details about my environment:**
* Brackets Version: Release 1.14 Build 1.14.2-17770 (release-1.14.2 f71f00acc) 
* Brackets Beautify Version: 2.10.0

**Before:**
`var a = b ?? [];`

**After:**
`var a= b ? ? [];`

The "Before" doesn't run into an error when executed, "After" returns the error " **Uncaught SyntaxError: Unexpected token '?'** " caused by the extra space inbetween the questionmarks.

[>Details and defenition of the nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_Coalescing_Operator)

**Comment by bitwiseman** [comment]
@DylanTim 

This is fixed v2.11.0.

**Comment by DylanTim** [comment]
@bitwiseman 

That's awesome, the latest release i can find in the brackets store is v2.10.0
When can I expect the update?

**Comment by bitwiseman** [comment]
@Hirse What has to happen here?

**Comment by DylanTim** [comment]
> @DylanTim
> 
> This is fixed v2.11.0.

@bitwiseman 
I have now downloaded the update manually (from [your official release "2.11.0 - js-beautify 1.11.0"](https://github.com/brackets-beautify/brackets-beautify/releases/tag/v2.11.0)) and installed it as a ZIP in brackets. 
The extension management now recognizes version 2.11.0 as installed, but even after restarting the program and the computer the mentioned problem does not seem to be solved.

After I beautified the issue-code on [the website of 
js-beautify](https://beautifier.io), the same thing happened as in Brackets, which confirms to me that the problem is not solved in v.2.11.0.

**Comment by bitwiseman** [comment]
Well this is embarrasing: https://github.com/beautify-web/js-beautify/issues/1794
Not fixed. Thanks for drawing my attention to it.

**Comment by bitwiseman** [comment]
@DylanTim 
Okay this time it really is fixed in js-beautify.

**Comment by DylanTim** [comment]
@bitwiseman 
Awesome!
I have just tried it and can confirm that it works flawlessly with the new version.
Thank you very much for your efforts.

**Comment by Hirse** [comment]
Thanks @bitwiseman for handling this.
There was an issue with the Brackets registry when I did the last (2.11) update and I must have forgotten to get back to it.
This should now be resolved with the latest update (2.12) this week.
