### ISSUE TITLE
Live Preview doubles elements when html is beatufied

### ISSUE THREAD

**Issue by MikeSpock** [brackets-beautify/brackets-beautify#49]
When I beautify my html, live preview doubles the active tags, only refresh fixes it.

**Comment by Denisov21** [comment]
https://github.com/adobe/brackets/pull/10653

**Comment by Denisov21** [comment]
https://github.com/adobe/brackets/issues/10634

**Comment by Hirse** [comment]
Thanks @Denisov21. I have a work-around for this on my fork, which I plan to merge shortly.

**Comment by Denisov21** [comment]
Wonderful @Hirse!

**Comment by MohabAli** [comment]
solved ... just disable (StaticServer)
go to ... Extension manager >> Default >> disable (StaticServer)
and use an alternative (Autosave) extension then enable (auto save (400 ms))
it will be in (File) after installation
https://github.com/nmaxcom/brackets-autosaver
run (live preview) enjoy
