### ISSUE TITLE
Multiple Comments in a Row Don't Format Properly

### ISSUE THREAD

**Issue by heatwaveo8** [brackets-beautify/brackets-beautify#63]
I am getting the following when consecutive rules have comments in CSS:

/* Comment 1 */

rule1 {
..........
}
/* Comment 2 */

rule2 {
..........
}

I would expect it to look like this:

/* Comment 1 */
rule1 {
..........
}

/* Comment 2 */
rule2 {
..........
}

**Comment by Hirse** [comment]
Please reopen this if the issue occurs again.
