### ISSUE TITLE
Beautify closes lines I want. Anyway around this?

### ISSUE THREAD

**Issue by keano12** [brackets-beautify/brackets-beautify#80]
I like a separate line between css rules. Does Beautify have an option where it won't close all the empty lines?

For example I prefer it this way:

h1, h2, h3, h4, h5, h6 {
    color: #222;
    font-weight: 600;
    line-height: 1.3em;
}

h2 {
    margin-top: 1.3em;
    border-bottom-style: double;
}

b, strong {
    font-weight: 600;
}

but after Beautifying it clears the lines like this:

h1, h2, h3, h4, h5, h6 {
    color: #222;
    font-weight: 600;
    line-height: 1.3em;
}
h2 {
    margin-top: 1.3em;
    border-bottom-style: double;
}
b, strong {
    font-weight: 600;
}

**Comment by Hirse** [comment]
The option `preserve_newlines` is only valid for js and html.
For CSS you have to use `newline_between_rules` which is enabled by default in the next version.

**Comment by depiction** [comment]
This is still unresolved. I'm using the default settings which have newline_between_rules set to true.

If I beautify the following:

`.divider {
	height: 1px;
	border-bottom: 1px solid #e5e5e5;
	margin-left: 8px;
	margin-right: 8px;
}
.item > {
	.icon {
		height: 32px;
		width: 32px;
		float: left;
	}
	.description {
		font-size: 12px;
		float: left;
		line-height: 14px;
		padding-left: 11px;
		width: 630px;
		> .header {
			font-size: 14px;
			margin-bottom: 5px;
			cursor: pointer;
			float: left;
			&:hover {
				text-decoration: underline;
			}
		}
	}
}
`

It becomes:

`.divider {
	height: 1px;
	border-bottom: 1px solid #e5e5e5;
	margin-left: 8px;
	margin-right: 8px;
}

.item > {
	.icon {
		height: 32px;
		width: 32px;
		float: left;
	}
	.description {
		font-size: 12px;
		float: left;
		line-height: 14px;
		padding-left: 11px;
		width: 630px;
		> .header {
			font-size: 14px;
			margin-bottom: 5px;
			cursor: pointer;
			float: left;
			&:hover {
				text-decoration: underline;
			}
		}
	}
}`

It correctly adds a new line between top level styles like .divider and .item, but not on child rules. When running Beautify I expect the following:

`.divider {
	height: 1px;
	border-bottom: 1px solid #e5e5e5;
	margin-left: 8px;
	margin-right: 8px;
}

.item > {
	.icon {
		height: 32px;
		width: 32px;
		float: left;
	}
	
	.description {
		font-size: 12px;
		float: left;
		line-height: 14px;
		padding-left: 11px;
		width: 630px;
		
		> .header {
			font-size: 14px;
			margin-bottom: 5px;
			cursor: pointer;
			float: left;
			
			&:hover {
				text-decoration: underline;
			}
		}
	}
}`

**Comment by Hirse** [comment]
@depiction the library is optimized for CSS, but your code doesn't seem to be standard CSS.
For better Less/Scss support please open an issue with js-beautify.

**Comment by bitwiseman** [comment]
`preserve_newlines` is also supported in the latest css-beautify.
