### ISSUE TITLE
formatter went crazy

### ISSUE THREAD

**Issue by e-cloud** [brackets-beautify/brackets-beautify#84]
my origin text
![image](https://cloud.githubusercontent.com/assets/5255354/2902405/785d17fa-d5e4-11e3-8b6e-41a21e0b4d1a.png)
after beautified
![image](https://cloud.githubusercontent.com/assets/5255354/2902417/8e277774-d5e4-11e3-8af6-cb0819328561.png)

is there a hot fix immediately?

**Comment by Hirse** [comment]
@joesatriani, the formatter cannot work correctly when you have syntax errors in your code, which as you can see from GitHub's pretty-printing is the case.
