### ISSUE TITLE
JSX and ReactJS Support

### ISSUE THREAD

**Issue by mattatcha** [brackets-beautify/brackets-beautify#85]
Would it be possible to have JSX and ReactJS support added? I am not able to use this on any of their files since it completely messes up any JSX.

**Comment by prettydiff** [comment]
http://prettydiff.com/ provides support for JSX.

Here are some brief code samples to try out: http://prettydiff.com/unit_tests/beautification_javascript_jsx.txt

Here is the concept of support: http://prettydiff.com/guide/react_jsx.xhtml

The github repo is: https://github.com/prettydiff/prettydiff
